import type { Producto } from './tipos'

export const catalogoSemilla: Producto[] = [
  {
    id: 1,
    nombre: 'iPhone 9',
    marca: 'Apple',
    categoria: 'smartphones',
    precio: 549,
    precioOriginal: 699,
    rating: 4.69,
    stock: 94,
    imagen: 'https://cdn.dummyjson.com/product-images/1/1.jpg',
    descripcion: 'El iPhone 9 une rendimiento y diseño con una cámara versátil para cada momento.',
  },
  {
    id: 2,
    nombre: 'Samsung Universe 9',
    marca: 'Samsung',
    categoria: 'smartphones',
    precio: 1249,
    precioOriginal: 1399,
    rating: 4.09,
    stock: 36,
    imagen: 'https://cdn.dummyjson.com/product-images/3/1.jpg',
    descripcion: 'Una experiencia premium para fotografía, multitarea y multimedia sin fricción.',
  },
  {
    id: 3,
    nombre: 'OPPOF19',
    marca: 'OPPO',
    categoria: 'smartphones',
    precio: 280,
    precioOriginal: 320,
    rating: 4.3,
    stock: 123,
    imagen: 'https://cdn.dummyjson.com/product-images/4/1.jpg',
    descripcion: 'Ligero, elegante y con autonomía para el día a día.',
  },
  {
    id: 4,
    nombre: 'Huawei P30',
    marca: 'Huawei',
    categoria: 'smartphones',
    precio: 499,
    precioOriginal: 599,
    rating: 4.09,
    stock: 32,
    imagen: 'https://cdn.dummyjson.com/product-images/5/1.jpg',
  },
  {
    id: 5,
    nombre: 'MacBook Pro',
    marca: 'Apple',
    categoria: 'laptops',
    precio: 1749,
    precioOriginal: 1999,
    rating: 4.57,
    stock: 83,
    imagen: 'https://cdn.dummyjson.com/product-images/6/1.jpg',
    descripcion: 'Potencia para edición, desarrollo y trabajo creativo en cualquier entorno.',
  },
  {
    id: 6,
    nombre: 'Samsung Galaxy Book',
    marca: 'Samsung',
    categoria: 'laptops',
    precio: 1499,
    precioOriginal: 1699,
    rating: 4.25,
    stock: 50,
    imagen: 'https://cdn.dummyjson.com/product-images/7/1.jpg',
  },
  {
    id: 7,
    nombre: 'Microsoft Surface Laptop 4',
    marca: 'Microsoft',
    categoria: 'laptops',
    precio: 1349,
    precioOriginal: 1549,
    rating: 4.43,
    stock: 68,
    imagen: 'https://cdn.dummyjson.com/product-images/8/1.jpg',
    descripcion: 'Diseño fino con pantalla brillante y desempeño sólido para estudiar y crear.',
  },
  {
    id: 8,
    nombre: 'Infinix INBOOK',
    marca: 'Infinix',
    categoria: 'laptops',
    precio: 1099,
    precioOriginal: 1299,
    rating: 4.54,
    stock: 96,
    imagen: 'https://cdn.dummyjson.com/product-images/9/1.jpg',
  },
]
